### ISSUE TITLE
Checklist for publishing the software

### ISSUE THREAD

**Issue by mwakok** [awegroup/AWE-Eco#17]
- [x] Add a [CITATION.cff file](https://citation-file-format.github.io/) to the root of the repository.
- [x] Check LICENSE
- [x] Add a file called `WAIVER` to the repository with the text
    ```
    Technische Universiteit Delft hereby disclaims all copyright interest in the
    program “[Software name]” ([add one line description of the content or function of the software])
    written by the Author(s).
    [Name Dean], Dean of [Name Faculty]
    ```
- [x] Add details on citing the software in the README
- [ ] Optional: add `.zenodo.json` metadata file to the root of the repository
- [x] Add dependencies (e.g. Matlab version) to the README
- [x] Update installation and execution instructions in the README
- [x] Add Contributing guide
- [ ] Optional: Add issue template for receiving questions/feedback
- [x] Obtain DOI through Zenodo by linking with GitHub releases
- [x] Optional: add [badges](https://shields.io/) for License, development status, DOI
- [x] Add `.gitignore` and remove MATLAB cache

**Comment by mwakok** [comment]
# TODO

## Before releasing
- [ ] Add ORCID to Citation.cff

## After releasing
- [ ] Add Zenodo DOI in Citation.cff
- [ ] Update software citation in README with Zenodo DOI
- [ ] Add Zenodo badge to README

**Comment by rishikeshsjoshi** [comment]
How should I update my CITATION.cff file to show the citation as in the README

Rishikesh Joshi and Filippo Trevisi (2024) "Reference Economic Model for Airborne Wind Energy Systems" (Version 1). IEA Wind TCP Task 48. https://doi.org/10.5281/zenodo.10959930.

**Comment by rishikeshsjoshi** [comment]
I removed the 'affiliation' entry in 'preferred-citation', which removed TU Delft as publisher. However, it still does not show 'IEA Wind TCP Task 48' as the publisher.

**Comment by edvinskis** [comment]
If you change `type: report` to `type: article`, the publisher will be shown.

Typically, the `type: report` is used for technical reports, which might not necessarily focus on the publisher but rather on the institution that issued the report. `type: article` is usually used for journal articles where the publisher is an essential element of the citation. 

This change should resolve the issue.

**Comment by rishikeshsjoshi** [comment]
Indeed, thanks!
